# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/ISE/hw/hw 1/hw.cache/wt} [current_project]
set_property parent.project_path {D:/ISE/hw/hw 1/hw.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/migrate/brick_board.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/migrate/vga_test.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/migrate/mem.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/migrate/MCPU_DEMO9.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/text.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/new_text.coe}}
add_files D:/ISE/E1339/m1/OExp13-SOC/ps2_tst.coe
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_new.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak1.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak2.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak3.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak4.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak5.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak6.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/ps2_tst_nobreak7.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_1.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_2.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_3.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_4.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_5.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_6.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_7.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_8.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/load_text.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/hw_9.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/new_1.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/new_2.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/final_arrow.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/final_arrow1.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/final_arrow2.coe}}
add_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/final_arrow23.coe}}
add_files -quiet {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/RAM_B.dcp}}
set_property used_in_implementation false [get_files {{D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/RAM_B.dcp}}]
add_files -quiet {{d:/ISE/hw/hw 1/hw.srcs/sources_1/ip/char_ram/char_ram.dcp}}
set_property used_in_implementation false [get_files {{d:/ISE/hw/hw 1/hw.srcs/sources_1/ip/char_ram/char_ram.dcp}}]
read_verilog -library xil_defaultlib {
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/ALU_v.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/Ext_32.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MC14495_ZJU.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/regs.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MUX4T1_5.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/REG32.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MUX2T1_32.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MUX4T1_32.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MUX8T1_8.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MUX2T1_64.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/SSeg_map.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/LEDP2S_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MDPath.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/HexTo8SEG.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MCtrl.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/P2S_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MUX8T1_32.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/VGA.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/SEnter_2_32_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/Display.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/clk_diff.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/PS2.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/PIO_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/clk_div.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/Multi_8CH32.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/GPIO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/Seg7_Dev_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MCPU.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/SAnti_jitter_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/Counter_3_IO.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/MIO_BUS.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/new/font_table.v}
  {D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/top.v}
}
read_edif {{D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/LEDP2S.ngc}}
read_edif {{D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/P2S.ngc}}
read_edif {{D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/SEnter_2_32.ngc}}
read_edif {{D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/Seg7_Dev.ngc}}
read_edif {{D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/SAnti_jitter.ngc}}
read_edif {{D:/ISE/hw/hw 1/hw.srcs/sources_1/imports/migrate/PIO.ngc}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/ISE/hw/hw 1/hw.srcs/constrs_1/imports/sources_1/contraints.xdc}}
set_property used_in_implementation false [get_files {{D:/ISE/hw/hw 1/hw.srcs/constrs_1/imports/sources_1/contraints.xdc}}]


synth_design -top top -part xc7k325tffg676-2L


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
