# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/RAM_B.xci
# IP: The module: 'RAM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/RAM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/RAM_B.xci
# IP: The module: 'RAM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ISE/hw/hw 1/hw.srcs/sources_1/ip/RAM_B_1/RAM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
