# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/char_ram/char_ram.xci
# IP: The module: 'char_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ISE/hw/hw 1/hw.srcs/sources_1/ip/char_ram/char_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/ISE/hw/hw 1/hw.srcs/sources_1/ip/char_ram/char_ram.xci
# IP: The module: 'char_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ISE/hw/hw 1/hw.srcs/sources_1/ip/char_ram/char_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
