set_property -dict {PACKAGE_PIN AC18 IOSTANDARD LVDS} [get_ports clk200P]
set_property -dict {PACKAGE_PIN AD18 IOSTANDARD LVDS} [get_ports clk200N]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS18} [get_ports RSTN]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS15} [get_ports {SW[0]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS15} [get_ports {SW[1]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS15} [get_ports {SW[2]}]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS15} [get_ports {SW[3]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS15} [get_ports {SW[4]}]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS15} [get_ports {SW[5]}]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVCMOS15} [get_ports {SW[6]}]
set_property -dict {PACKAGE_PIN AD10 IOSTANDARD LVCMOS15} [get_ports {SW[7]}]
set_property -dict {PACKAGE_PIN AE10 IOSTANDARD LVCMOS15} [get_ports {SW[8]}]
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVCMOS15} [get_ports {SW[9]}]
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVCMOS15} [get_ports {SW[10]}]
set_property -dict {PACKAGE_PIN AE8 IOSTANDARD LVCMOS15} [get_ports {SW[11]}]
set_property -dict {PACKAGE_PIN AF8 IOSTANDARD LVCMOS15} [get_ports {SW[12]}]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS15} [get_ports {SW[13]}]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS15} [get_ports {SW[14]}]
set_property -dict {PACKAGE_PIN AF10 IOSTANDARD LVCMOS15} [get_ports {SW[15]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS18} [get_ports {K_ROW[0]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS18} [get_ports {K_ROW[1]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS18} [get_ports {K_ROW[2]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS18} [get_ports {K_ROW[3]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS18} [get_ports {K_ROW[4]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS18} [get_ports {K_COL[0]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS18} [get_ports {K_COL[1]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS18} [get_ports {K_COL[2]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS18} [get_ports {K_COL[3]}]
#set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS18} [get_ports {K_COL[4]}]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports LEDCLK]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports LEDEN]
set_property -dict {PACKAGE_PIN M26 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports LEDDT]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS33} [get_ports SEGCLK]
set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVCMOS33} [get_ports SEGDT]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports SEGEN]
#set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports tri_led0_r_n]
#set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports tri_led0_g_n]
#set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports tri_led0_b_n]
#set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33} [get_ports tri_led1_r_n]
#set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports tri_led1_g_n]
#set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVCMOS33} [get_ports tri_led1_b_n]
#set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[0]}]
#set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[1]}]
#set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[2]}]
#set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[3]}]
#set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[4]}]
#set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[5]}]
#set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[6]}]
#set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[7]}]
#set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[8]}]
#set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[9]}]
#set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[10]}]
#set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[11]}]
#set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[12]}]
#set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[13]}]
#set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[14]}]
#set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[15]}]
#set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[16]}]
#set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[17]}]
#set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[18]}]
#set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[19]}]
#set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ce_n[0]}]
#set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ce_n[1]}]
#set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ce_n[2]}]
#set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[0]}]
#set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[1]}]
#set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[2]}]
#set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[3]}]
#set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[4]}]
#set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[5]}]
#set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[6]}]
#set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[7]}]
#set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[8]}]
#set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[9]}]
#set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[10]}]
#set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[11]}]
#set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[12]}]
#set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[13]}]
#set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[14]}]
#set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[15]}]
#set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[16]}]
#set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[17]}]
#set_property -dict {PACKAGE_PIN A24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[18]}]
#set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[19]}]
#set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[20]}]
#set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[21]}]
#set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[22]}]
#set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[23]}]
#set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[24]}]
#set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[25]}]
#set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[26]}]
#set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[27]}]
#set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[28]}]
#set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[29]}]
#set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[30]}]
#set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[31]}]
#set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[32]}]
#set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[33]}]
#set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[34]}]
#set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[35]}]
#set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[36]}]
#set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[37]}]
#set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[38]}]
#set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[39]}]
#set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[40]}]
#set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[41]}]
#set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[42]}]
#set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[43]}]
#set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[44]}]
#set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[45]}]
#set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[46]}]
#set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[47]}]
#set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_oe_n[0]}]
#set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_oe_n[1]}]
#set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_oe_n[2]}]
#set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_we_n[0]}]
#set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_we_n[1]}]
#set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_we_n[2]}]
#set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ub_n[0]}]
#set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ub_n[1]}]
#set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ub_n[2]}]
#set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_lb_n[0]}]
#set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_lb_n[1]}]
#set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_lb_n[2]}]
#set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[0]}]
#set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[1]}]
#set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[2]}]
#set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[3]}]
#set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[4]}]
#set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[5]}]
#set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[6]}]
#set_property -dict {PACKAGE_PIN J8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[7]}]
#set_property -dict {PACKAGE_PIN F9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[8]}]
#set_property -dict {PACKAGE_PIN F8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[9]}]
#set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[10]}]
#set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[11]}]
#set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[12]}]
#set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[13]}]
#set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[14]}]
#set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[15]}]
#set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[16]}]
#set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[17]}]
#set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[18]}]
#set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[19]}]
#set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[20]}]
#set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[21]}]
#set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[22]}]
#set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[23]}]
#set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ce_n[0]}]
#set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ce_n[1]}]
#set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[0]}]
#set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[1]}]
#set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[2]}]
#set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[3]}]
#set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[4]}]
#set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[5]}]
#set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[6]}]
#set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[7]}]
#set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[8]}]
#set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[9]}]
#set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[10]}]
#set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[11]}]
#set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[12]}]
#set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[13]}]
#set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[14]}]
#set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[15]}]
#set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[16]}]
#set_property -dict {PACKAGE_PIN J25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[17]}]
#set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[18]}]
#set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[19]}]
#set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[20]}]
#set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[21]}]
#set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[22]}]
#set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[23]}]
#set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[24]}]
#set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[25]}]
#set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[26]}]
#set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[27]}]
#set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[28]}]
#set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[29]}]
#set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[30]}]
#set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[31]}]
#set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports flash_oe_n]
#set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports flash_rst_n]
#set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ready[0]}]
#set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ready[1]}]
#set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports flash_we_n]
#set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS33 SLEW FAST PULLUP true} [get_ports uart_rx]
#set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 16 PULLUP true} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports PS2A_CLK_OUT]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports PS2A_DATA_OUT]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports vga_h_sync]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports vga_v_sync]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[0]}]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[1]}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[2]}]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[3]}]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[0]}]
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[1]}]
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[2]}]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[3]}]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[0]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[1]}]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[2]}]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[3]}]
#set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS33} [get_ports sd_clk]
#set_property -dict {PACKAGE_PIN AD25 IOSTANDARD LVCMOS33} [get_ports sd_cmd]
#set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS33} [get_ports {sd_dat[0]}]
#set_property -dict {PACKAGE_PIN AE22 IOSTANDARD LVCMOS33} [get_ports {sd_dat[1]}]
#set_property -dict {PACKAGE_PIN AF22 IOSTANDARD LVCMOS33} [get_ports {sd_dat[2]}]
#set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33} [get_ports {sd_dat[3]}]
#set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVCMOS33} [get_ports sd_cd]
#set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS33} [get_ports sd_rst]
set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33} [get_ports Buzzer]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[0]}]
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[1]}]
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[2]}]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[3]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[4]}]
set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[5]}]
set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[6]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS33} [get_ports {SEGMENT[7]}]
set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
set_property -dict {PACKAGE_PIN AE21 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports {LED[4]}]
set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS33} [get_ports {LED[5]}]
set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVCMOS33} [get_ports {LED[6]}]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports {LED[7]}]
##set_property -dict {PACKAGE_PIN AC18 IOSTANDARD LVDS} [get_ports clk_p]
##set_property -dict {PACKAGE_PIN AD18 IOSTANDARD LVDS} [get_ports clk_n]
#set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS18} [get_ports rst_n]
#set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS15} [get_ports {switch[0]}]
#set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS15} [get_ports {switch[1]}]
#set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS15} [get_ports {switch[2]}]
#set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS15} [get_ports {switch[3]}]
#set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS15} [get_ports {switch[4]}]
#set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS15} [get_ports {switch[5]}]
#set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVCMOS15} [get_ports {switch[6]}]
#set_property -dict {PACKAGE_PIN AD10 IOSTANDARD LVCMOS15} [get_ports {switch[7]}]
#set_property -dict {PACKAGE_PIN AE10 IOSTANDARD LVCMOS15} [get_ports {switch[8]}]
#set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVCMOS15} [get_ports {switch[9]}]
#set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVCMOS15} [get_ports {switch[10]}]
#set_property -dict {PACKAGE_PIN AE8 IOSTANDARD LVCMOS15} [get_ports {switch[11]}]
#set_property -dict {PACKAGE_PIN AF8 IOSTANDARD LVCMOS15} [get_ports {switch[12]}]
#set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS15} [get_ports {switch[13]}]
#set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS15} [get_ports {switch[14]}]
#set_property -dict {PACKAGE_PIN AF10 IOSTANDARD LVCMOS15} [get_ports {switch[15]}]
#set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS18} [get_ports {btn_x[0]}]
#set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS18} [get_ports {btn_x[1]}]
#set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS18} [get_ports {btn_x[2]}]
#set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS18} [get_ports {btn_x[3]}]
#set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS18} [get_ports {btn_x[4]}]
#set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS18} [get_ports {btn_y[0]}]
#set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS18} [get_ports {btn_y[1]}]
#set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS18} [get_ports {btn_y[2]}]
#set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS18} [get_ports {btn_y[3]}]
#set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS18} [get_ports {btn_y[4]}]
#set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports led_clk]
#set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports led_pen]
#set_property -dict {PACKAGE_PIN M26 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports led_do]
#set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS33} [get_ports seg_clk]
#set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVCMOS33} [get_ports seg_do]
#set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports seg_pen]
#set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports tri_led0_r_n]
#set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports tri_led0_g_n]
#set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports tri_led0_b_n]
#set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33} [get_ports tri_led1_r_n]
#set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports tri_led1_g_n]
#set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVCMOS33} [get_ports tri_led1_b_n]
#set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[0]}]
#set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[1]}]
#set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[2]}]
#set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[3]}]
#set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[4]}]
#set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[5]}]
#set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[6]}]
#set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[7]}]
#set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[8]}]
#set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[9]}]
#set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[10]}]
#set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[11]}]
#set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[12]}]
#set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[13]}]
#set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[14]}]
#set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[15]}]
#set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[16]}]
#set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[17]}]
#set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[18]}]
#set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_addr[19]}]
#set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ce_n[0]}]
#set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ce_n[1]}]
#set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ce_n[2]}]
#set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[0]}]
#set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[1]}]
#set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[2]}]
#set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[3]}]
#set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[4]}]
#set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[5]}]
#set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[6]}]
#set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[7]}]
#set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[8]}]
#set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[9]}]
#set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[10]}]
#set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[11]}]
#set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[12]}]
#set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[13]}]
#set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[14]}]
#set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[15]}]
#set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[16]}]
#set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[17]}]
#set_property -dict {PACKAGE_PIN A24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[18]}]
#set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[19]}]
#set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[20]}]
#set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[21]}]
#set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[22]}]
#set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[23]}]
#set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[24]}]
#set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[25]}]
#set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[26]}]
#set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[27]}]
#set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[28]}]
#set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[29]}]
#set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[30]}]
#set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[31]}]
#set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[32]}]
#set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[33]}]
#set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[34]}]
#set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[35]}]
#set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[36]}]
#set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[37]}]
#set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[38]}]
#set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[39]}]
#set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[40]}]
#set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[41]}]
#set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[42]}]
#set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[43]}]
#set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[44]}]
#set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[45]}]
#set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[46]}]
#set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_data[47]}]
#set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_oe_n[0]}]
#set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_oe_n[1]}]
#set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_oe_n[2]}]
#set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_we_n[0]}]
#set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_we_n[1]}]
#set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_we_n[2]}]
#set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ub_n[0]}]
#set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ub_n[1]}]
#set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_ub_n[2]}]
#set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_lb_n[0]}]
#set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_lb_n[1]}]
#set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 4} [get_ports {sram_lb_n[2]}]
#set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[0]}]
#set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[1]}]
#set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[2]}]
#set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[3]}]
#set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[4]}]
#set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[5]}]
#set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[6]}]
#set_property -dict {PACKAGE_PIN J8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[7]}]
#set_property -dict {PACKAGE_PIN F9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[8]}]
#set_property -dict {PACKAGE_PIN F8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[9]}]
#set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[10]}]
#set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[11]}]
#set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[12]}]
#set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[13]}]
#set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[14]}]
#set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[15]}]
#set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[16]}]
#set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[17]}]
#set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[18]}]
#set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[19]}]
#set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[20]}]
#set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[21]}]
#set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[22]}]
#set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_addr[23]}]
#set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ce_n[0]}]
#set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ce_n[1]}]
#set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[0]}]
#set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[1]}]
#set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[2]}]
#set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[3]}]
#set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[4]}]
#set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[5]}]
#set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[6]}]
#set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[7]}]
#set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[8]}]
#set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[9]}]
#set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[10]}]
#set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[11]}]
#set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[12]}]
#set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[13]}]
#set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[14]}]
#set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[15]}]
#set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[16]}]
#set_property -dict {PACKAGE_PIN J25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[17]}]
#set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[18]}]
#set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[19]}]
#set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[20]}]
#set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[21]}]
#set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[22]}]
#set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[23]}]
#set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[24]}]
#set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[25]}]
#set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[26]}]
#set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[27]}]
#set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[28]}]
#set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[29]}]
#set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[30]}]
#set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_data[31]}]
#set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports flash_oe_n]
#set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports flash_rst_n]
#set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ready[0]}]
#set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {flash_ready[1]}]
#set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports flash_we_n]
#set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS33 SLEW FAST PULLUP true} [get_ports uart_rx]
#set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 16 PULLUP true} [get_ports uart_tx]
#set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports PS2A_CLK_OUT]
#set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports PS2A_DATA_OUT]
#set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports vga_h_sync]
#set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports vga_v_sync]
#set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[0]}]
#set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[1]}]
#set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[2]}]
#set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_blue[3]}]
#set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[0]}]
#set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[1]}]
#set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[2]}]
#set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_green[3]}]
#set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[0]}]
#set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[1]}]
#set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[2]}]
#set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {vga_red[3]}]
#set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS33} [get_ports sd_clk]
#set_property -dict {PACKAGE_PIN AD25 IOSTANDARD LVCMOS33} [get_ports sd_cmd]
#set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS33} [get_ports {sd_dat[0]}]
#set_property -dict {PACKAGE_PIN AE22 IOSTANDARD LVCMOS33} [get_ports {sd_dat[1]}]
#set_property -dict {PACKAGE_PIN AF22 IOSTANDARD LVCMOS33} [get_ports {sd_dat[2]}]
#set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33} [get_ports {sd_dat[3]}]
#set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVCMOS33} [get_ports sd_cd]
#set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS33} [get_ports sd_rst]
#set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33} [get_ports buzzer]
#set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports {segment[0]}]
#set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS33} [get_ports {segment[1]}]
#set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS33} [get_ports {segment[2]}]
#set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports {segment[3]}]
#set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {segment[4]}]
#set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVCMOS33} [get_ports {segment[5]}]
#set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVCMOS33} [get_ports {segment[6]}]
#set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS33} [get_ports {segment[7]}]
#set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS33} [get_ports {an[0]}]
#set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS33} [get_ports {an[1]}]
#set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {an[2]}]
#set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports {an[3]}]
#set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS33} [get_ports {a_led[0]}]
#set_property -dict {PACKAGE_PIN AE21 IOSTANDARD LVCMOS33} [get_ports {a_led[1]}]
#set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports {a_led[2]}]
#set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33} [get_ports {a_led[3]}]
#set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports {a_led[4]}]
#set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS33} [get_ports {a_led[5]}]
#set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVCMOS33} [get_ports {a_led[6]}]
#set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports {a_led[7]}]
 